import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import type { NextPage } from "next";
import Head from "next/head";

import { useDispatch } from "react-redux";
import { decrement, increment } from "./../app/slices/counter";

const Home: NextPage = () => {
  const dispatch = useDispatch();

  return (
    <Box sx={{ backgroundColor: "#fff", minHeight: "100vh", color: "#000" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button variant="outlined" onClick={() => dispatch(increment)}>
          +
        </Button>
        <Button variant="outlined" onClick={() => dispatch(decrement)}>
          -
        </Button>
      </div>
    </Box>
  );
};

export default Home;
